pool: 
  name: Default

steps:
- script: echo %PATH%
  displayName: 'Print PATH'

- script: dir "C:\Program Files\Git\bin\bash.exe"
  displayName: 'Check Bash Location'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: env

variables:
  BASH_ENV: "~/.profile"