pool: 
  name: Default

steps:
- powershell: echo $env:PATH
  displayName: 'Print PATH'

- powershell: Get-Command bash
  displayName: 'Check Bash Location'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: env

variables:
  BASH_ENV: "~/.profile"