trigger:
- '*'

pool: 
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  BASH_ENV: "~/.profile"

steps:
- script: echo %PATH%
  displayName: 'Print PATH'

- script: dir "C:\Program Files\Git\bin\bash.exe"
  displayName: 'Check Bash Location'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: env

- script: |
    set PATH=C:\Users\acer\.nvm\versions\node\v12.22.12\bin;%PATH%
    echo "Updated PATH: %PATH%"
  displayName: 'Set npm and node.js path'

- script: |
    if exist "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" (
        echo "PowerShell found"
        set PATH=C:\Windows\System32\WindowsPowerShell\v1.0;%PATH%
    ) else (
        echo "PowerShell not found"
        exit /b 1
    )
    echo "Updated PATH with PowerShell: %PATH%"
  displayName: 'Ensure PowerShell is available'

- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'
