pool: 
  name: Default

steps:
- script: echo %PATH%
  displayName: 'Print PATH'


- script: where bash
  displayName: 'Check Bash Location'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: env

variables:
  BASH_ENV: "~/.profile"